### ISSUE TITLE
Building and installing on Windows

### ISSUE THREAD

**Issue by nxths** [sbidin/sdl2-image#1]
These bindings won't build + install on Windows currently due to a [bug involving GHC, Windows, and Template Haskell](https://github.com/haskell-game/sdl2/issues/41#issuecomment-73564593).  I made a [Windows branch](https://github.com/nxths/sdl2-image) with a crude workaround if anyone else is trying to do this.

**Comment by sbidin** [comment]
It's probably a good idea to expand the templates as you've done, to get rid of the template-haskell dependency. If issues like these continue to crop up, I'll do so as well. Hopefully the Windows issue you've experienced has since been fixed.

**Comment by nxths** [comment]
https://ghc.haskell.org/trac/ghc/ticket/3242 was fixed in GHC 8.0.1 (or maybe the version earlier I forget) so the bindings build + install without issue on Windows now, thanks!

**Comment by sbidin** [comment]
Awesome! Thanks for letting me know.

**Comment by sgraf812** [comment]
It seems like with the appropriate two defines, the build goes through, but any example I tried that depended on this library did not produce a window at all and immediately exits (c.f. https://github.com/jxv/dino-rush/pull/1)
