### ISSUE TITLE
please upload to hackage

### ISSUE THREAD

**Issue by simonmichael** [sbidin/sdl2-image#3]
Thanks for the lib updates, which work with the latest sdl2 lib. Please upload this up-to-date version over https://hackage.haskell.org/package/sdl2-image-0.1.3.2 , so that modern buildable SDL libs are easy to find on Hackage.

**Comment by sbidin** [comment]
Note though that I don't control sdl2-image on Hackage, and my version of sdl2-image probably isn't compatible with @ccll's. I'll try contacting him and seeing what he thinks about merging our repositories.

**Comment by sbidin** [comment]
Looks like @ccll's email address doesn't work anymore.

Cai, if you can read this, please shoot me an email at sinisa@bidin.eu.

**Comment by simonmichael** [comment]
Ah, there's also https://github.com/ccll/hs-sdl2-image/issues/7 open since last year and https://github.com/ccll/hs-sdl2-image/pull/8 9 days ago.

**Comment by sbidin** [comment]
Sadly, I could not get in touch with @ccll, even though they seem to have been active on Github three weeks ago. So I'm not sure what, if anything, I should do at this point.

**Comment by simonmichael** [comment]
I also tried emailing on 10/18. In a case like this I think it's fine to upload your fixed version, updating the Author and Maintainer fields as needed. You could also send an "intent to take over" announcement to haskell-cafe.

**Comment by ccll** [comment]
Sorry guys! I've been really busy lately, I'm afraid I don't have the time to maintain the Hackage package, and I will no longer doing Haskell programming in forseeable future, is there any way I can transfer the control to @sbidin ?

**Comment by ccll** [comment]
@sbidin OK I've found out that I can add your Hackage username to the maintainer list, this is the fastest way to get your package uploaded and override my deprecated one, please tell me your username and I'll add it ASAP.

**Comment by sbidin** [comment]
@ccll Hi Cai, no worries, I know how busy it can get. My username on Hackage is `SinisaBidin`.  I hope we'll see you working with Haskell again soon!

**Comment by ccll** [comment]
@sbidin I've tried to add you to the maintainer list, but nothing happened after I click the "Add Member" button, I guess may be a mail has been send to you in the background silently. Please check your mailbox and let me know if anything goes wrong.

**Comment by sbidin** [comment]
@ccll I received no notification, but I checked and am now in the sdl2-image maintainers group, so all seems to be well. Thanks!

**Comment by sbidin** [comment]
Thanks for the help, everyone. The library should now be accessible over Hackage.

**Comment by simonmichael** [comment]
Thanks! 2017 will be the year of Haskell in Games Development!

**Comment by ccll** [comment]
@sbidin Great! I'm glad to help.  😄
