### ISSUE TITLE
Not building on windows

### ISSUE THREAD

**Issue by nitrix** [sbidin/sdl2-image#5]
Could it be that sdl2-image needs the same fix as sdl2-ttf ?

```
if os(windows)
    cpp-options: -D_SDL_main_h
```

**Comment by sbidin** [comment]
I don't have access to a Windows machine at this time, so any comments on this are very welcome.

**Comment by Rain92** [comment]
I can confirm this.

```
if os(windows) 
    cpp-options: -D_SDL_main_h
```

Has to be added to the .cabal file or it won't install. Same issue with sdl2-gfx.
